import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const API = "http://localhost:5000/api";

function Login({ onLogin }) {
  const [email, setEmail] = useState("srikar@example.com");
  const [password, setPassword] = useState("student123");
  const [error, setError] = useState("");
  async function submit(event) {
    event.preventDefault(); setError("");
    try {
      const response = await fetch(`${API}/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.message);
      onLogin(data);
    } catch (err) { setError(err.message || "Unable to sign in."); }
  }
  return <main className="login-page"><section className="login-art"><p className="eyebrow">EDTECH / STUDENT PORTAL</p><h1>Your academic life, in one clear place.</h1><p>Stay ahead of attendance, coursework, results and campus requests without chasing paperwork.</p><div className="login-stat"><strong>24/7</strong><span>access to your academic workspace</span></div></section><section className="login-card"><div className="brand-mark">E<span>.</span></div><p className="eyebrow">WELCOME BACK</p><h2>Sign in to continue</h2><p className="muted">Use your student account to open your dashboard.</p><form onSubmit={submit} className="login-form"><label>Email address<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <div className="error">{error}</div>}<button className="primary full">Sign in</button></form><p className="login-hint">Demo account: srikar@example.com / student123</p></section></main>;
}

function App() {
  const [student, setStudent] = useState(null); const [active, setActive] = useState("Dashboard"); const [message, setMessage] = useState("");
  const [data, setData] = useState({ courses: [], records: [], requests: [], notifications: [], attendance: [], handouts: [], assignments: [] });
  async function loadData(id = student?.student_id) {
    if (!id) return;
    try { const names = ["courses", "records", "requests", "notifications", "attendance", "handouts", "assignments"]; const responses = await Promise.all(names.map(name => fetch(`${API}/students/${id}/${name}`).then(r => r.json()))); setData(Object.fromEntries(names.map((name, index) => [name, responses[index]]))); }
    catch { setMessage("Backend is not reachable. Start the backend on port 5000."); }
  }
  useEffect(() => { if (student) loadData(); }, [student]);
  if (!student) return <Login onLogin={profile => { setStudent(profile); loadData(profile.student_id); }} />;
  const nav = ["Dashboard", "Courses & Handouts", "Attendance", "Academic Records", "Assignments", "Requests", "Notifications"];
  return <div className="app"><aside className="sidebar"><div className="logo"><span>E</span> EdTech</div><p className="side-label">STUDENT WORKSPACE</p><nav>{nav.map(item => <button key={item} className={active === item ? "nav active" : "nav"} onClick={() => setActive(item)}><span className="nav-icon">{icon(item)}</span><span>{item}</span></button>)}</nav><div className="sidebar-bottom"><div className="online-dot">● <span>Portal online</span></div><button className="logout" onClick={() => setStudent(null)}>↪ Sign out</button></div></aside><main className="main"><header><div><p className="eyebrow">{active === "Dashboard" ? "OVERVIEW" : "STUDENT SERVICES"}</p><h1>{active}</h1></div><div className="profile-mini"><div className="avatar">{student.student_name[0]}</div><div><strong>{student.student_name}</strong><small>{student.department}</small></div></div></header>{message && <div className="message">{message}</div>}{active === "Dashboard" && <Dashboard student={student} data={data} setActive={setActive} />}{active === "Courses & Handouts" && <Courses data={data} />}{active === "Attendance" && <Attendance data={data} setActive={setActive} />}{active === "Academic Records" && <Records records={data.records} />}{active === "Assignments" && <Assignments data={data} reload={loadData} setMessage={setMessage} studentId={student.student_id} />}{active === "Requests" && <Requests data={data} reload={loadData} setMessage={setMessage} studentId={student.student_id} />}{active === "Notifications" && <Notifications items={data.notifications} />}</main></div>;
}

function icon(item) { return ({ Dashboard: "⌂", "Courses & Handouts": "▣", Attendance: "◔", "Academic Records": "⌁", Assignments: "↑", Requests: "✎", Notifications: "○" })[item]; }
function attendanceAverage(items) { return items.length ? Math.round(items.reduce((sum, item) => sum + Number(item.percentage), 0) / items.length) : 0; }
function Dashboard({ student, data, setActive }) { const low = data.attendance.filter(item => Number(item.percentage) < 75).length; return <><section className="welcome"><div><p className="eyebrow">MONDAY, 14 SEPTEMBER 2026</p><h2>Good morning, {student.student_name.split(" ")[0]}.</h2><p>Your workspace is ready. Keep an eye on attendance and upcoming coursework.</p></div><button className="primary" onClick={() => setActive("Assignments")}>Upload assignment <span>↗</span></button></section><div className="metric-grid"><Metric label="Enrolled courses" value={data.courses.length} detail="This semester" tone="coral" /><Metric label="Average attendance" value={`${attendanceAverage(data.attendance)}%`} detail="Across all subjects" tone="teal" /><Metric label="Assignments sent" value={data.assignments.length} detail="Uploaded by you" tone="gold" /><Metric label="Unread updates" value={data.notifications.length} detail="Latest from faculty" tone="lilac" /></div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">ATTENDANCE PULSE</p><h3>Keep your rhythm</h3></div><button className="text-button" onClick={() => setActive("Attendance")}>View details →</button></div><div className="attendance-summary"><strong>{attendanceAverage(data.attendance)}<small>%</small></strong><div><b>Overall attendance</b><p>{low ? `${low} subject${low > 1 ? "s" : ""} need attention.` : "You are on track across your subjects."}</p></div></div><div className="mini-bars">{data.attendance.map(item => <div key={item.attendance_id}><span style={{ height: `${Math.min(Number(item.percentage), 100)}%` }}></span><small>{item.course_code}</small></div>)}</div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">LATEST</p><h3>Notifications</h3></div><button className="text-button" onClick={() => setActive("Notifications")}>See all →</button></div>{data.notifications.slice(0, 3).map(item => <div className="list-row" key={item.notification_id}><span className="list-dot"></span><div><b>{item.title}</b><p>{item.message}</p></div></div>)}</section></div></>; }
function Metric({ label, value, detail, tone }) { return <div className={`metric ${tone}`}><span className="metric-mark"></span><p>{label}</p><strong>{value}</strong><small>{detail}</small></div>; }
function Courses({ data }) { return <div className="course-grid">{data.courses.map(course => <article className="course-card" key={course.course_id}><div className="course-top"><span>{course.course_code}</span><b>{course.credits} credits</b></div><h3>{course.course_name}</h3><p>{course.faculty_name} · {course.semester}</p><div className="handout-block"><p className="eyebrow">SUBJECT HANDOUTS</p>{data.handouts.filter(item => item.course_code === course.course_code).map(item => <a href={item.file_url} target="_blank" rel="noreferrer" key={item.handout_id}>↗ {item.title}</a>)}</div></article>)}</div>; }
function Attendance({ data, setActive }) { return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">SEMESTER OVERVIEW</p><h3>Attendance by subject</h3></div><div className="panel-actions"><span className="threshold">Minimum target: 75%</span><button className="outline" onClick={() => setActive("Requests")}>Request digital letter</button></div></div><div className="attendance-list">{data.attendance.map(item => <div className="attendance-row" key={item.attendance_id}><div><b>{item.course_code}</b><span>{item.course_name}</span></div><strong className={Number(item.percentage) < 75 ? "low" : "good"}>{item.percentage}%</strong><div className="progress"><i style={{ width: `${Math.min(Number(item.percentage), 100)}%` }}></i></div><small>{item.classes_attended} of {item.classes_held} classes attended</small><button className="outline" onClick={() => setActive("Requests")}>Send absence letter</button></div>)}</div></section>; }
function Records({ records }) { return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">PERFORMANCE</p><h3>Academic records</h3></div></div><Table headers={["Course", "Subject", "Marks", "Grade", "Semester"]} rows={records.map(item => [item.course_code, item.course_name, `${item.marks}/100`, item.grade, item.semester])} /></section>; }
function Assignments({ data, reload, setMessage, studentId }) { const [form, setForm] = useState({ course_id: "", title: "", file: null }); const [busy, setBusy] = useState(false); async function submit(event) { event.preventDefault(); if (!form.file) return setMessage("Choose a file before uploading."); setBusy(true); const reader = new FileReader(); reader.onload = async () => { const response = await fetch(`${API}/students/${studentId}/assignments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ course_id: form.course_id, title: form.title, file_name: form.file.name, file_data: reader.result }) }); const result = await response.json(); setBusy(false); if (!response.ok) return setMessage(result.message); setForm({ course_id: "", title: "", file: null }); setMessage("Assignment uploaded successfully."); reload(); }; reader.readAsDataURL(form.file); } return <><section className="panel"><div className="panel-heading"><div><p className="eyebrow">SUBMIT WORK</p><h3>Upload an assignment</h3></div></div><form className="assignment-form" onSubmit={submit}><label>Subject<select value={form.course_id} onChange={e => setForm({ ...form, course_id: e.target.value })} required><option value="">Select a subject</option>{data.courses.map(course => <option value={course.course_id} key={course.course_id}>{course.course_code} · {course.course_name}</option>)}</select></label><label>Assignment title<input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="e.g. SQL normalization exercise" required /></label><label className="file-drop">{form.file ? `Selected: ${form.file.name}` : "Choose a file to upload"}<input type="file" onChange={e => setForm({ ...form, file: e.target.files[0] })} required /><small>PDF, DOC, DOCX, PPT, or ZIP · up to 10 MB</small></label><button className="primary" disabled={busy}>{busy ? "Uploading..." : "Upload assignment"}</button></form></section><section className="panel"><div className="panel-heading"><h3>Submission history</h3></div><Table headers={["Subject", "Assignment", "File", "Submitted"]} rows={data.assignments.map(item => [item.course_code, item.title, item.file_name, new Date(item.submitted_at).toLocaleString()])} /></section></>; }
function Requests({ data, reload, setMessage, studentId }) { const [type, setType] = useState("Absence Letter"); const [description, setDescription] = useState(""); async function submit(event) { event.preventDefault(); const response = await fetch(`${API}/students/${studentId}/requests`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ request_type: type, description }) }); if (response.ok) { setDescription(""); setMessage("Request submitted successfully."); reload(); } else setMessage("Could not submit request."); } return <><section className="panel"><div className="panel-heading"><div><p className="eyebrow">STUDENT SERVICES</p><h3>Send a request</h3></div></div><form className="request-form" onSubmit={submit}><label>Request type<select value={type} onChange={e => setType(e.target.value)}><option>Absence Letter</option><option>Bonafide Certificate</option><option>Course Registration</option><option>Transcript</option><option>Other Academic Request</option></select></label><label>Explain your request<textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Tell your faculty or administration what you need..." required /></label><button className="primary">Submit request</button></form></section><section className="panel"><div className="panel-heading"><h3>Request history</h3></div><Table headers={["Type", "Description", "Status", "Created"]} rows={data.requests.map(item => [item.request_type, item.description, item.status, new Date(item.created_at).toLocaleString()])} /></section></>; }
function Notifications({ items }) { return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">UPDATES</p><h3>Notifications</h3></div></div>{items.map(item => <div className="notification" key={item.notification_id}><span className="list-dot"></span><div><b>{item.title}</b><p>{item.message}</p><small>{new Date(item.created_at).toLocaleString()}</small></div></div>)}</section>; }
function Table({ headers, rows }) { return <div className="table-wrap"><table><thead><tr>{headers.map(header => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, i) => <tr key={i}>{row.map((value, j) => <td key={j}>{String(value)}</td>)}</tr>) : <tr><td colSpan={headers.length}>No data available yet.</td></tr>}</tbody></table></div>; }

createRoot(document.getElementById("root")).render(<App />);